### ISSUE TITLE
Setting one pin (WiringPi Pin 4) to `LOW` changes another (WiringPi Pin 5) pin to `LOW`

### ISSUE THREAD

**Issue by cr1901** [TinkerBoard/gpio_lib_c#2]
## Issue
I am using commit 9fdbe332. I have supplied a [test_case](https://github.com/TinkerBoard/gpio_lib_c/files/2152271/gpio_bug.tar.gz) along w/ some diagrams from my logic analyzer.

The test case is the following, and it was adapted from code from [ArduinoOPL2](https://github.com/DhrBaksteen/ArduinoOPL2):

```
#include <wiringPi.h>
#include <wiringPiSPI.h>

#include <unistd.h>


#define PIN_LATCH 1                             // GPIO header pin 12
#define PIN_ADDR  4                             // GPIO header pin 16
#define PIN_RESET 5                             // GPIO header pin 18

// SPI setup for WiringPi.
#define SPI_SPEED   8000000
#define SPI_CHANNEL 0

int main()
{
    wiringPiSetup();

    pinMode(PIN_ADDR, OUTPUT);
    pinMode(PIN_RESET,   OUTPUT);

    digitalWrite(PIN_RESET,   HIGH);
#ifdef SHOW_BUG
    digitalWrite(PIN_ADDR, LOW);
#endif

    return 0;
}
```

When `PIN_ADDR` is written `LOW`, `PIN_RESET` is also pulled `LOW`. I would expect that writing to a single pin would not affect the logic level of any other pins.

## Traces
When `SHOW_BUG` is _not_ defined, and I run the above test program, my logic analyzer attached to the TinkerBoard's pins show the following trace (note that I set `RESET` low ahead-of-time):
![image](https://user-images.githubusercontent.com/6418027/42129855-bcda98d8-7c9f-11e8-8ddf-325f6561cb17.png)

On the other hand, if `SHOW_BUG` is defined, and I run the above test program, I get this trace as output:
![image](https://user-images.githubusercontent.com/6418027/42129838-075c80ca-7c9f-11e8-88ee-34c056169592.png)

Closeup of glitch on `RESET` line:
![image](https://user-images.githubusercontent.com/6418027/42129841-2018addc-7c9f-11e8-8c9b-21a0daddc8c3.png)

The traces were captured with a trigger of low-to-high transition on the `RESET` line.

**Comment by scorpiochang** [comment]
Hi cr1901

This mistake is put address as mov parameter, and use it as operand.
`‵`               __asm__ volatile(
                "mov r0,%0\n\t"
                "mov r1,%1\n\t"
                "orr r0,r1\n\t"
                "str r0,[%0]\n\t"
                :
                :"r" (**addr**),"r" (op)
                :"r0","r1"
                );`‵`
I already use ldr instruction instead of mov instruction, but i observed low latency when ldr instruction load content from memory. finally, this issue should be fix. thank you.

https://github.com/TinkerBoard/gpio_lib_c/commit/57d4c4be7157414bed397a5cf655299bb74b2535

**Comment by cr1901** [comment]
I can confirm at least for pins 4 and 5, the issue is fixed (although the music coming from [my kit](https://github.com/DhrBaksteen/ArduinoOPL2) still doesn't sound good lol). I'll reopen the issue if I find any new bugs.

Thanks for the help as always!
